### ISSUE TITLE
allow multilines

### ISSUE THREAD

**Issue by AlbanMinassian** [zaytsev/fluent-static#1]
Bonjour, merci pour votre projet qui est intéressant

- est-ce que les traductions globales (`-sync-brand-name = Firefox Account`) sont possibles ? 
- est-ce que les traductions "multilines" seront un jour possible ? 
- 
Cordialement
Alban

**Comment by zaytsev** [comment]
Hello,

fluent terms/private messages

```fluent
# Private message
-brand-name = MyApplication

# Public message exposed in the UI, using the private message
welcome-msg = Welcome to { -brand-name }!
```
are not currently supported, but it is on roadmap.

Multiline messages are supported, just make sure your editor uses spaces as fluent specs requires https://projectfluent.org/fluent/guide/multiline.html
