### ISSUE TITLE
How to set `language_cookie_name` for all requests?

### ISSUE THREAD

**Issue by uwe-nanninga** [zaytsev/fluent-static#14]
Hello,

I am using the `axum` feature and need guidance on using `RequestLanguageConfig`.

I want the configuration to:

1. Use `language_cookie` as the primary source for language selection.
2. Fallback to the `Accept-Language` header if the cookie is not set.
3. Default to a pre-defined language if no supported language is found.

While looking through the source code I found the following test:
https://github.com/zaytsev/fluent-static/blob/main/crates/lib/src/support.rs#L202-L228

I believe setting `ignore_accept_language_header` to `false` would achieve the desired behavior, but I'm unsure where to adjust this configuration to ensure it applies to all requests.

**Comment by zaytsev** [comment]
You need to set [axum request extension](https://docs.rs/axum/latest/axum/#using-request-extensions).
Something like
```rust

let request_lang_config = RequestLanguageConfig::builder().language_cookie_name("lang").build();

let app = Router::new()
    .route("/", get(handler))
    .layer(Extension(request_lang_config));
```
