### ISSUE TITLE
Replacement for FunctionPerMessageCodeGenerator

### ISSUE THREAD

**Issue by leecbaker** [zaytsev/fluent-static#18]
I've been using the [`FunctionPerMessageCodeGenerator`](https://docs.rs/fluent-static-codegen/0.5.0/fluent_static_codegen/codegen/struct.FunctionPerMessageCodeGenerator.html) from `fluent-static-codegen` v0.5 to generate a single function per string to be translated.

It appears that v0.6 removes this functionality entirely, leaving only the ability to work with bundles. Is there a plan to re-introduce the function-per-message generation, or do I need to move projects to use bundles instead?

Here's what my code currently looks like:
```rust
let src = generate(
        "../l10n/",
        FunctionPerMessageCodeGenerator::new_with_options(
            "en",
            FluentBundleOptions {
                use_isolating: false,
                transform_fn: None,
                format_fn: None,
            },
        ),
    )
```

Thanks for making a great and useful tool!

**Comment by zaytsev** [comment]
There was a major rewrite of codegen stuff between 0.5 and 0.6 and it is now focused on message bundles. I find message bundle structs approach more ergonomic and don't have plans to support function-per-message codegen strategy.

I'd suggest to migrate to the new procmacro/codegen style, but it is not mandatory if legacy codegen works for you.

**Comment by zaytsev** [comment]
Btw, number formatter has changed significantly in v0.5. So the latest `fluent-static` provides two options by default: either use "full" power of ICU number formatter which also requires native ICU dependency or no number formatter at all. 
While `fluent-bundle` (the lib `fluent-static-codegen` pre v0.6 relies on) has some basic number formatting support builtin. 
So if you decide to migrate to the latest `fluent-static` then I'd recommend to check if numbers are formatted as expected

**Comment by leecbaker** [comment]
Thanks for the update @zaytsev . I'll make the change.
