### ISSUE TITLE
Add support for attributes

### ISSUE THREAD

**Issue by nazar-pc** [zaytsev/fluent-static#8]
Right now attributes seem to be ignored in method generation, would be nice to support them though

**Comment by zaytsev** [comment]
Named variables feature as mentioned in #9 will also support attributes, e.g. `my_message().attr_1()`

As for adding support for attributes to the existing function-style code generators.. I could only think of a special convention like `my_message__attr1(..)` two `_` will separate message name from attribute name

**Comment by nazar-pc** [comment]
I was mostly expecting something like `my_message_attr_1`, any benefit to use chained function calls?
