### ISSUE TITLE
Arguments are ordered alphabetically rather than in the order of their occurrence

### ISSUE THREAD

**Issue by nazar-pc** [zaytsev/fluent-static#9]
This:
```
test = {$b} {$a}
```

For some reason will generated a function like this:
```
fn test(&self, $a, $b) -> Message
```

Which is confusing since `$b` is used before `$a` and it would be more natural to order arguments accordingly (while skipping duplicates of course).

**Comment by zaytsev** [comment]
Agree. It should probably use the order of variables as in default language message definition.

**Comment by zaytsev** [comment]
Still could be confusing in some situations.

I'm working on a builder-style named variables support like

```Rust
my_message().var_a(a_value).var_b(b_value)?
```
Don't have any ETA though

**Comment by nazar-pc** [comment]
I just ended up adding `a_`, `b_` and so on to all of them in order to make position predictable. Could be just documented I guess.
